# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11rkevvI8GC41d7DqdEHo8whn9wEnIKyL
"""

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm1=cv2.imread("rasm1.jpg")
cv2_imshow(rasm1)

rasm2=cv2.imread("rasm2.jpg")
cv2_imshow(rasm2)

rasm3=cv2.imread("rasm3.jpg")
cv2_imshow(rasm3)

rasm4=cv2.imread("rasm4.jpg")
cv2_imshow(rasm4)

rasm5=cv2.imread("rasm5.jpg")
cv2_imshow(rasm5)

oqqora1=cv2.cvtColor(rasm1, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora1)

oqqora2=cv2.cvtColor(rasm2, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora2)

oqqora3=cv2.cvtColor(rasm3, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora3)

oqqora4=cv2.cvtColor(rasm4, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora4)

oqqora5=cv2.cvtColor(rasm5, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora5)